import { Product, DashboardStats } from './types';

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Aether Noise-Canceling Headphones',
    subtitle: 'Studio-quality sound anywhere',
    price: 299,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    type: 'direct',
    badge: 'NEW',
    rating: 4.8,
    reviewCount: 124,
    description: 'Immerse yourself in pure audio with our flagship noise-canceling headphones. Featuring 40mm custom drivers and 30-hour battery life.',
    features: ['Active Noise Cancellation', '30-hour battery', 'Bluetooth 5.3', 'Custom tactile controls'],
    pros: ['Exceptional sound clarity', 'All-day comfort', 'Premium build quality'],
    cons: ['Carrying case is bulky', 'No water resistance rating']
  },
  {
    id: 'p2',
    name: 'Nomad Canvas Tote',
    subtitle: 'Daily essentials carrier',
    price: 85,
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80',
    type: 'affiliate',
    affiliateUrl: 'https://example.com/partner-tote',
    rating: 4.6,
    reviewCount: 389,
    description: 'A durable, stylish tote bag perfect for everyday use. Made from sustainable heavy-weight organic canvas.',
    pros: ['Spacious interior', 'Eco-friendly materials', 'Durable straps'],
    cons: ['Lacks internal zipper pockets']
  },
  {
    id: 'p3',
    name: 'Suede Loafers',
    subtitle: 'Italian Leather',
    price: 120,
    image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&q=80',
    type: 'affiliate',
    badge: "Editor's Pick",
    rating: 4.9,
    reviewCount: 56,
    affiliateUrl: 'https://example.com/partner-shoes',
    description: 'Handcrafted in Italy using premium suede. These loafers offer unmatched comfort without compromising on style.',
    pros: ['Extremely comfortable out of box', 'Versatile styling', 'High-quality stitching'],
    cons: ['Requires suede protector spray', 'Sizing runs slightly large']
  },
  {
    id: 'p4',
    name: 'Mineral Face Sunscreen',
    subtitle: 'SPF 50 Broad Spectrum',
    price: 34,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&q=80',
    type: 'direct',
    badge: 'SALE',
    rating: 4.5,
    reviewCount: 210,
    description: 'A lightweight, non-greasy mineral sunscreen that blends completely transparent on all skin tones.',
    pros: ['No white cast', 'Reef safe formulation', 'Works well under makeup'],
    cons: ['Slightly thicker consistency', 'Higher price point for size']
  },
  {
    id: 'p5',
    name: 'Ceramic Pour-Over Kettle',
    subtitle: 'Precision brewing',
    price: 65,
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80',
    type: 'affiliate',
    rating: 4.7,
    reviewCount: 89,
    affiliateUrl: 'https://example.com/kettle'
  },
  {
    id: 'p6',
    name: 'Linen Blend Throw',
    subtitle: 'Textured comfort',
    price: 110,
    image: 'https://images.unsplash.com/photo-1584345290616-e41b9d4f0d61?w=800&q=80',
    type: 'direct',
    rating: 4.9,
    reviewCount: 42
  },
  {
    id: 'p7',
    name: 'Mechanical Keyboard v2',
    subtitle: 'Tactile typing experience',
    price: 145,
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&q=80',
    type: 'affiliate',
    badge: 'NEW',
    rating: 4.8,
    reviewCount: 312,
    affiliateUrl: 'https://example.com/kb'
  },
  {
    id: 'p8',
    name: 'Aroma Diffuser Stone',
    subtitle: 'Essential oil companion',
    price: 45,
    image: 'https://images.unsplash.com/photo-1602928321679-560bb453f190?w=800&q=80',
    type: 'direct',
    rating: 4.4,
    reviewCount: 78
  },
  // Row 2 products
  {
    id: 'p9',
    name: 'Cashmere Turtleneck',
    subtitle: 'Soft luxury knitwear',
    price: 180,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80',
    type: 'direct',
    badge: 'LIMITED EDITION',
    rating: 4.9,
    reviewCount: 34,
    description: 'Ultra-soft Mongolian cashmere turtleneck in a relaxed silhouette. A timeless piece that transcends seasons.',
    pros: ['Incredibly soft texture', 'Versatile neutral tone', 'Perfect drape'],
    cons: ['Requires dry cleaning', 'Premium price point']
  },
  {
    id: 'p10',
    name: 'Artisan Leather Wallet',
    subtitle: 'Hand-stitched vegetable tan',
    price: 75,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80',
    type: 'affiliate',
    badge: 'SALE',
    rating: 4.7,
    reviewCount: 156,
    affiliateUrl: 'https://example.com/wallet',
    description: 'A slim bifold wallet crafted from full-grain vegetable-tanned leather that develops a rich patina over time.',
    pros: ['Beautiful aging leather', 'Slim profile', 'RFID blocking'],
    cons: ['Stiff when new', 'Limited card slots']
  },
  {
    id: 'p11',
    name: 'Smart Home Hub',
    subtitle: 'Voice-controlled ecosystem',
    price: 129,
    image: 'https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=800&q=80',
    type: 'direct',
    badge: 'NEW',
    rating: 4.6,
    reviewCount: 203,
    description: 'The central brain for your connected home. Compatible with 5000+ devices and voice assistants.',
    pros: ['Seamless integration', 'Privacy-first design', 'Compact form factor'],
    cons: ['Setup can be complex', 'Subscription for advanced features']
  },
  {
    id: 'p12',
    name: 'Organic Matcha Set',
    subtitle: 'Ceremonial grade tea',
    price: 55,
    image: 'https://images.unsplash.com/photo-1582793988951-9aed5509eb97?w=800&q=80',
    type: 'affiliate',
    rating: 4.8,
    reviewCount: 91,
    affiliateUrl: 'https://example.com/matcha',
    description: 'A complete matcha ceremony set including ceremonial grade powder, bamboo whisk, and ceramic bowl.',
    pros: ['Vibrant green color', 'Smooth umami flavor', 'Beautiful presentation box'],
    cons: ['Whisk requires care', 'Small serving size']
  },
  // Row 3 products
  {
    id: 'p13',
    name: 'Minimalist Desk Lamp',
    subtitle: 'Warm LED task lighting',
    price: 89,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
    type: 'direct',
    badge: 'LIMITED EDITION',
    rating: 4.5,
    reviewCount: 67,
    description: 'A sculptural desk lamp with adjustable color temperature and wireless charging base.',
    pros: ['Stunning design', 'Wireless charging built-in', 'Eye-friendly light'],
    cons: ['Limited height adjustment', 'Fingerprints show easily']
  },
  {
    id: 'p14',
    name: 'Wool Overshirt',
    subtitle: 'Heavyweight flannel',
    price: 135,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80',
    type: 'affiliate',
    badge: 'SALE',
    rating: 4.7,
    reviewCount: 118,
    affiliateUrl: 'https://example.com/overshirt',
    description: 'A rugged overshirt woven from Italian melton wool. The perfect layering piece for transitional weather.',
    pros: ['Substantial weight', 'Rich texture', 'Versatile styling'],
    cons: ['Heavy for warm climates', 'Dry clean recommended']
  },
  {
    id: 'p15',
    name: 'Portable Espresso Maker',
    subtitle: 'Manual pressure brew',
    price: 95,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdc?w=800&q=80',
    type: 'direct',
    badge: 'NEW',
    rating: 4.4,
    reviewCount: 145,
    description: 'Brew cafe-quality espresso anywhere with this hand-powered portable machine. No electricity required.',
    pros: ['True crema extraction', 'Ultra-portable', 'No pods needed'],
    cons: ['Requires practice', 'Small water reservoir']
  },
  {
    id: 'p16',
    name: 'Silk Sleep Mask',
    subtitle: '22 momme mulberry silk',
    price: 38,
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800&q=80',
    type: 'affiliate',
    rating: 4.6,
    reviewCount: 289,
    affiliateUrl: 'https://example.com/sleepmask',
    description: 'A luxuriously soft sleep mask made from the finest 22 momme mulberry silk for the ultimate beauty sleep.',
    pros: ['Gentle on skin', 'Blocks all light', 'Adjustable strap'],
    cons: ['Requires hand washing', 'Slight color fading over time']
  },
  // Row 4 products
  {
    id: 'p17',
    name: 'Ceramic Vase Set',
    subtitle: 'Hand-thrown stoneware',
    price: 68,
    image: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=800&q=80',
    type: 'direct',
    badge: 'NEW',
    rating: 4.7,
    reviewCount: 52,
    description: 'A trio of organic-shaped ceramic vases in warm earth tones. Each piece is uniquely hand-thrown by artisans.',
    pros: ['Unique organic shapes', 'Versatile sizing', 'Beautiful glaze finish'],
    cons: ['Fragile during shipping', 'Limited batch sizes']
  },
  {
    id: 'p18',
    name: 'Leather Weekender',
    subtitle: 'Full-grain travel bag',
    price: 245,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    type: 'affiliate',
    badge: 'LIMITED EDITION',
    rating: 4.8,
    reviewCount: 31,
    affiliateUrl: 'https://example.com/weekender',
    description: 'A spacious weekender bag crafted from thick full-grain leather with brass hardware. Ages beautifully.',
    pros: ['Generous capacity', 'Durable construction', 'Timeless design'],
    cons: ['Heavy when fully packed', 'Premium price point']
  },
  {
    id: 'p19',
    name: 'Bamboo Cutting Board',
    subtitle: 'End-grain butcher block',
    price: 42,
    image: 'https://images.unsplash.com/photo-1626139588087-248792dc9e1b?w=800&q=80',
    type: 'direct',
    badge: 'SALE',
    rating: 4.5,
    reviewCount: 178,
    description: 'A thick end-grain bamboo cutting board that is gentle on knives and naturally antimicrobial.',
    pros: ['Knife-friendly surface', 'Sustainable material', 'Easy to clean'],
    cons: ['Requires regular oiling', 'Not dishwasher safe']
  },
  {
    id: 'p20',
    name: 'Wireless Earbuds Pro',
    subtitle: 'Active noise cancellation',
    price: 159,
    image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80',
    type: 'affiliate',
    rating: 4.6,
    reviewCount: 412,
    affiliateUrl: 'https://example.com/earbuds',
    description: 'Premium true wireless earbuds with adaptive ANC, spatial audio, and 30-hour total battery life.',
    pros: ['Crystal clear calls', 'Secure fit', 'Quick charge feature'],
    cons: ['Case is slightly bulky', 'Touch controls can be sensitive']
  }
];

export const mockDashboardStats: DashboardStats = {
  totalClicks: 12458,
  estRevenue: 4350.75,
  directSales: 18900.00,
  revenueTrend: [
    { name: 'Mon', revenue: 1200, clicks: 400 },
    { name: 'Tue', revenue: 1900, clicks: 600 },
    { name: 'Wed', revenue: 1400, clicks: 450 },
    { name: 'Thu', revenue: 2100, clicks: 800 },
    { name: 'Fri', revenue: 2800, clicks: 1200 },
    { name: 'Sat', revenue: 3200, clicks: 1500 },
    { name: 'Sun', revenue: 2900, clicks: 1300 },
  ]
};
